github: ShivamPingaleDev
ko_fi: shivampingaledev
liberapay: ShivamPingaleDev
custom:
  - https://github.com/sponsors/ShivamPingaleDev
  - https://buymeacoffee.com/shivampingaledev
  - https://ko-fi.com/shivampingaledev
  - https://liberapay.com/ShivamPingaleDev/donate
