#!/bin/sh
# Rebuild overlay inventories and the re-applicable src patch from the pinned
# VeraCrypt commit. Run after you change ports/overlay/src, before a release.
#
#   scripts/refresh-overlay.sh
#   scripts/refresh-overlay.sh --check   # exit 1 if lists/patch are stale

set -eu

ROOT=$(CDPATH= git rev-parse --show-toplevel)
cd "$ROOT"

PIN_FILE=ports/UPSTREAM_COMMIT
OWNED=ports/overlay/owned.txt
PATCHED=ports/overlay/patched.txt
REPLACE=ports/overlay/replace.txt
FLAT=ports/OVERLAY.files
PATCH=ports/overlay/src-port.patch
SKIP=ports/overlay/mobile-skip.txt
CMAKE=ports/shared/upstream-sources.cmake
OVERLAY_SRC=ports/overlay/src

PIN=$(tr -d '[:space:]' < "$PIN_FILE")
if ! git cat-file -e "$PIN^{commit}" 2>/dev/null; then
	echo "Pin $PIN is not a commit in this repo." >&2
	exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

{
	echo "# Files that do not exist in upstream VeraCrypt. After a merge, restore these"
	echo "# wholesale. Regenerated with: scripts/refresh-overlay.sh"
	{
		git diff --name-only --diff-filter=A "$PIN" -- src/ PORTING.md scripts/ || true
		git ls-files --others --exclude-standard -- src/ PORTING.md scripts/ || true
		printf '%s\n' \
			PORTING.md \
			scripts/sync-upstream.sh \
			scripts/refresh-overlay.sh \
			scripts/check-upstream-layout.sh
	} | awk 'NF && $0 !~ /^#/ && !seen[$0]++'
} > "$tmp/owned.txt"

{
	echo "# Upstream VeraCrypt files this port still edits in src/. Keep this empty."
	echo "# Phone hunks belong in ports/overlay/src/ (see replace.txt)."
	echo "# Snapshot: ports/overlay/src-port.patch (scripts/refresh-overlay.sh)."
	git diff --name-only --diff-filter=M "$PIN" -- src/
} > "$tmp/patched.txt"

{
	echo "# Phone replacements compiled or included instead of the same path under src/."
	echo "# src/ stays official VeraCrypt. Regenerated by scripts/refresh-overlay.sh."
	if [ -d "$OVERLAY_SRC" ]; then
		find "$OVERLAY_SRC" -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.mm' \) \
			| sed "s|^$OVERLAY_SRC/||" | sort
	fi
} > "$tmp/replace.txt"

{
	echo "# Deprecated flat list. Prefer ports/overlay/owned.txt + replace.txt."
	echo "# Kept so older docs still point somewhere. Regenerated by scripts/refresh-overlay.sh."
	grep -v '^#' "$tmp/owned.txt" | grep -v '^$'
	grep -v '^#' "$tmp/replace.txt" | grep -v '^$' | while IFS= read -r rel; do
		printf '%s\n' "$OVERLAY_SRC/$rel"
	done
} > "$tmp/flat.txt"

# Patch of overlay replacements vs the official pin (not vs dirty src/).
# Twin trees under $tmp/tree keep git paths: a/src/... b/ports/overlay/src/...
: > "$tmp/src-port.patch"
replace_files=$(grep -v '^#' "$tmp/replace.txt" | grep -v '^$' || true)
if [ -n "$replace_files" ]; then
	echo "$replace_files" | while IFS= read -r rel; do
		[ -z "$rel" ] && continue
		mkdir -p "$tmp/tree/src/$(dirname "$rel")" "$tmp/tree/ports/overlay/src/$(dirname "$rel")"
		git show "$PIN:src/$rel" > "$tmp/tree/src/$rel"
		cp "$OVERLAY_SRC/$rel" "$tmp/tree/ports/overlay/src/$rel"
	done
	# git diff --no-index exits 1 when files differ; keep the patch.
	(cd "$tmp/tree" && git diff --no-index -- src ports/overlay/src || true) \
		> "$tmp/src-port.patch"
fi

{
	echo "# Crypto/Volume units present in VeraCrypt but not compiled by VC Port."
	echo "# After a VeraCrypt merge, new files show up as extras in check-upstream-layout.sh"
	echo "# until you add them to cmake or refresh this skip list on purpose."
	grep -E '\$\{VC_SRC\}/' "$CMAKE" | sed 's/.*\${VC_SRC}\///; s/).*//; s/[[:space:]]*$//' | sort -u > "$tmp/listed"
	find src/Crypto src/Volume -type f \( -name '*.c' -o -name '*.cpp' \) ! -path '*/Argon2/src/test*' \
		| sed 's|^src/||' | sort -u | while IFS= read -r rel; do
			grep -Fxq "$rel" "$tmp/listed" && continue
			printf '%s\n' "$rel"
		done
} > "$tmp/skip.txt"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [ "$CHECK" = 1 ]; then
	fail=0
	for pair in "$OWNED:$tmp/owned.txt" "$PATCHED:$tmp/patched.txt" "$REPLACE:$tmp/replace.txt" "$FLAT:$tmp/flat.txt" "$PATCH:$tmp/src-port.patch" "$SKIP:$tmp/skip.txt"; do
		a=${pair%%:*}
		b=${pair#*:}
		if [ ! -f "$a" ] || ! cmp -s "$a" "$b"; then
			echo "stale: $a (run scripts/refresh-overlay.sh)"
			fail=1
		fi
	done
	exit "$fail"
fi

mkdir -p ports/overlay
cp "$tmp/owned.txt" "$OWNED"
cp "$tmp/patched.txt" "$PATCHED"
cp "$tmp/replace.txt" "$REPLACE"
cp "$tmp/flat.txt" "$FLAT"
cp "$tmp/src-port.patch" "$PATCH"
cp "$tmp/skip.txt" "$SKIP"
echo "Wrote $OWNED, $PATCHED, $REPLACE, $FLAT, $PATCH, $SKIP"
echo "Pin $PIN"
patched=$(grep -v '^#' "$PATCHED" | grep -v '^$' || true)
if [ -n "$patched" ]; then
	echo "WARNING: src/ still differs from the pin (should be empty):" >&2
	echo "$patched" >&2
fi
