#!/bin/sh
# Rebuild overlay inventories and the re-applicable src patch from the pinned
# VeraCrypt commit. Run after you change src/ port hunks, before a release.
#
#   scripts/refresh-overlay.sh
#   scripts/refresh-overlay.sh --check   # exit 1 if lists/patch are stale

set -eu

ROOT=$(CDPATH= git rev-parse --show-toplevel)
cd "$ROOT"

PIN_FILE=ports/UPSTREAM_COMMIT
OWNED=ports/overlay/owned.txt
PATCHED=ports/overlay/patched.txt
FLAT=ports/OVERLAY.files
PATCH=ports/overlay/src-port.patch
SKIP=ports/overlay/mobile-skip.txt
CMAKE=ports/shared/upstream-sources.cmake

PIN=$(tr -d '[:space:]' < "$PIN_FILE")
if ! git cat-file -e "$PIN^{commit}" 2>/dev/null; then
	echo "Pin $PIN is not a commit in this repo." >&2
	exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

{
	echo "# Files that do not exist in upstream VeraCrypt. After a merge, restore these"
	echo "# wholesale. Regenerate with: scripts/refresh-overlay.sh"
	{
		git diff --name-only --diff-filter=A "$PIN" HEAD -- src/ PORTING.md scripts/ || true
		git ls-files --others --exclude-standard -- src/ PORTING.md scripts/ || true
		printf '%s\n' \
			PORTING.md \
			scripts/sync-upstream.sh \
			scripts/refresh-overlay.sh \
			scripts/check-upstream-layout.sh
	} | awk 'NF && $0 !~ /^#/ && !seen[$0]++'
} > "$tmp/owned.txt"

{
	echo "# Upstream VeraCrypt files this port edits. Never restore these from a pre-merge"
	echo "# copy — that would drop VeraCrypt's own changes. Git 3-way merge them."
	echo "# Snapshot: ports/overlay/src-port.patch (scripts/refresh-overlay.sh)."
	git diff --name-only --diff-filter=M "$PIN" HEAD -- src/
} > "$tmp/patched.txt"

{
	echo "# Deprecated flat list. Prefer ports/overlay/owned.txt + patched.txt."
	echo "# Kept so older docs still point somewhere. Regenerated by scripts/refresh-overlay.sh."
	grep -v '^#' "$tmp/owned.txt" | grep -v '^$'
	grep -v '^#' "$tmp/patched.txt" | grep -v '^$'
} > "$tmp/flat.txt"

# Patch of modified upstream files only (owned files are complete copies).
patched_files=$(grep -v '^#' "$tmp/patched.txt" | grep -v '^$' || true)
if [ -n "$patched_files" ]; then
	# shellcheck disable=SC2086
	git diff "$PIN" HEAD -- $patched_files > "$tmp/src-port.patch"
else
	: > "$tmp/src-port.patch"
fi

{
	echo "# Crypto/Volume units present in VeraCrypt but not compiled by VC Port."
	echo "# After a VeraCrypt merge, new files show up as extras in check-upstream-layout.sh"
	echo "# until you add them to cmake or refresh this skip list on purpose."
	grep -E '\$\{VC_SRC\}/' "$CMAKE" | sed 's/.*\${VC_SRC}\///; s/).*//; s/[[:space:]]*$//' | sort -u > "$tmp/listed"
	find src/Crypto src/Volume -type f \( -name '*.c' -o -name '*.cpp' \) ! -path '*/Argon2/src/test*' \
		| sed 's|^src/||' | sort -u | while IFS= read -r rel; do
			grep -Fxq "$rel" "$tmp/listed" && continue
			printf '%s\n' "$rel"
		done
} > "$tmp/skip.txt"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [ "$CHECK" = 1 ]; then
	fail=0
	for pair in "$OWNED:$tmp/owned.txt" "$PATCHED:$tmp/patched.txt" "$FLAT:$tmp/flat.txt" "$PATCH:$tmp/src-port.patch" "$SKIP:$tmp/skip.txt"; do
		a=${pair%%:*}
		b=${pair#*:}
		if [ ! -f "$a" ] || ! cmp -s "$a" "$b"; then
			echo "stale: $a (run scripts/refresh-overlay.sh)"
			fail=1
		fi
	done
	exit "$fail"
fi

mkdir -p ports/overlay
cp "$tmp/owned.txt" "$OWNED"
cp "$tmp/patched.txt" "$PATCHED"
cp "$tmp/flat.txt" "$FLAT"
cp "$tmp/src-port.patch" "$PATCH"
cp "$tmp/skip.txt" "$SKIP"
echo "Wrote $OWNED, $PATCHED, $FLAT, $PATCH, $SKIP"
echo "Pin $PIN"
